### ISSUE TITLE
Ownership of the table

### ISSUE THREAD

**Issue by danieldk** [BurntSushi/suffix#2]
I had a question, or perhaps suggestion, but I am new to Rust, so I might be missing something: the `SuffixTable` struct stores the text as `Cow`, but the actual table/array as a vector that is always owned. I wondered if you considered making the table `Cow` as well.

The immediate benefit that I see is that one could write the constructed table to disk and then later use the `SuffixTable` using a memory mapped table via `from_parts`.

I made a quick modification to use `Cow` for the `table` member and all unit tests pass.

**Comment by BurntSushi** [comment]
I think that sounds pretty reasonable. I think `SuffixTable` would need to grow another lifetime parameter, which would be a breaking change, but I have no problem with that. So I'd say submit the PR! :-)

(There's no particular reason why it isn't already a `Cow`, I just didn't think of the use case.)

**Comment by danieldk** [comment]
Thanks for merging the pull request and uploading a new version!
