### ISSUE TITLE
Performances

### ISSUE THREAD

**Issue by delehef** [BurntSushi/suffix#8]
Hi,

I needed a high performance suffix array lib some time ago for a bioinformatics project, and I ended up working with a crude FFI with [divsufsort](https://github.com/y-256/libdivsufsort).

Just so you know, its performances while creating the array is blowing _suffix_ out of the water. So feel free to take a glance if it interests you or to close this issue otherwise ;)

**Comment by BurntSushi** [comment]
> Just so you know, its performances while creating the array is blowing suffix out of the water.

Can you please show your benchmarks? Otherwise, I'm not really sure what to do with this issue.

**Comment by delehef** [comment]
My issue was a bit off the mill and I apologize if I went off as confrontational.

[Here is](https://github.com/delehef/suffixes) a toy repo with a minimal example; you just have to `gunzip` the `msy.fasta.gz` file before either `cargo bench`- or `cargo run`-ing – I advise you to run it normally first, the benchmark mode is awfully long in this case. In my computer, I have these results:

```
18 matches
PT3.080668480S seconds for divsufsort.
18 matches
PT9.860067663S seconds for suffix.
```

**Comment by delehef** [comment]
Neither; it is much more crude and it only works when looking for bytes in a bytes array. I just thought you might be interesting by their algorithm.

**Comment by BurntSushi** [comment]
Thanks! I'll take a look at this when I get a chance.

**Comment by delehef** [comment]
You're most welcome! On an aside, thanks for everything you're doing in the Rust community.

**Comment by BurntSushi** [comment]
I'm going to close this out as stale. If I ever get motivated enough to dive back into this space, then I'll investigate performance more closely, but I'm otherwise happy with where this crate is currently at.
